name: Build fusionsolar-data-fetcher

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build fusionsolar-data-fetcher
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v6

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      # Set up Gradle (includes wrapper validation and dependency graph submission)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true
          dependency-graph: generate-and-submit

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build JAR file with Gradle
      - name: Build JAR file
        run: ./gradlew build

      # Upload JAR artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: fusionsolar-data-fetcher
          path: build/libs/*.jar
          retention-days: 7
